services:
  oven_machine:
    build:
      context: /home/smart/Project-AI-CCTV/code_run_ubuntu
      dockerfile: docker/Dockerfile
    volumes:
      - /home/smart/Project-AI-CCTV/code_run_ubuntu:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Bangkok
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /app
    command: python main_run_oven_machine.py
    restart: always

  analyze:
        build:
          context: /home/smart/Project-AI-CCTV/code_run_ubuntu
          dockerfile: docker/Dockerfile
        volumes:
          - /home/smart/Project-AI-CCTV/code_run_ubuntu:/app
        working_dir: /app
        command: python python_analyze.py
        restart: always
        network_mode: host
        environment:
          - TZ=Asia/Bangkok
        healthcheck:
          test: ["CMD", "pgrep", "-f", "python_analyze"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 10s

  oven_machine_b:
      build:
        context: /home/smart/Project-AI-CCTV/code_run_ubuntu
        dockerfile: docker/Dockerfile
      volumes:
        - /home/smart/Project-AI-CCTV/code_run_ubuntu:/app
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      network_mode: host
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - TZ=Asia/Bangkok
      deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
      working_dir: /app
      command: python main_run_oven_machine_b.py
      restart: always

  analyze_b:
        build:
          context: /home/smart/Project-AI-CCTV/code_run_ubuntu
          dockerfile: docker/Dockerfile
        volumes:
          - /home/smart/Project-AI-CCTV/code_run_ubuntu:/app
        working_dir: /app
        command: python python_analyze_b.py
        restart: always
        network_mode: host
        environment:
          - TZ=Asia/Bangkok
        healthcheck:
          test: ["CMD", "pgrep", "-f", "python_analyze"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 10s




