version: "3.8"

services:
  ai_app:
    build:
      context: /home/smart/Project-AI-CCTV/code_run_ubuntu
      dockerfile: docker/Dockerfile
    volumes:
      - /home/smart/Project-AI-CCTV/code_run_ubuntu:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Bangkok
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /app
    command: python main_run_oven_machine.py
