version: "3.8"

services:
  ai_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /app
    command: python main_run_oven_machine.py
